## Simple ve Multiple Linear regression

In [2]:
import pandas as pd
import numpy as np

In [3]:
# veriyi oku
df = pd.read_csv('Power_Plant.csv', delimiter=",")
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [59]:
# girdileri ve çıktı sutunlarını x ve y değişkenine ata
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [60]:
# Veri setini Eğitim seti ve Test seti olarak ayırma
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [61]:
# Standard Scaling

from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()
x_train_scaled = standard_scaler.fit_transform(x_train)
x_test_scaled = standard_scaler.transform(x_test)

In [62]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train_scaled,y_train)

LinearRegression()

In [63]:
y_pred = regressor.predict(x_test_scaled)

y_pred_df = pd.DataFrame(data=y_pred,columns=["Tahmini_Sonuc"])

In [64]:
y_test_df = pd.DataFrame(data=y_test,columns=["Gerçek_Sonuç"])

karsılastırma_df = pd.concat([y_test_df,y_pred_df],axis=1)
karsılastırma_df

Gerçek_Sonuç  Tahmini_Sonuc
0           440.17     438.038829
1           450.86     448.223550
2           441.76     439.962454
3           464.95     464.137305
4           467.62     467.208206
...            ...            ...
1889        430.92     437.623002
1890        466.83     466.445187
1891        446.75     454.009410
1892        449.99     452.231097
1893        440.46     440.081215

[1894 rows x 2 columns]

In [65]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9227358762491314

In [66]:
unseen_dataset_df = pd.read_csv('Power_Plant_Unseen.csv', delimiter=";")
unseen_dataset_df.head(10)

AT      V       AP     RH
0  12.45  40.56  1017.84  66.52
1  16.70  40.56  1019.04  50.90
2  19.88  44.60  1015.52  37.85
3  19.64  46.33  1013.33  98.99
4  20.01  59.87  1019.00  84.12
5  16.27  58.20  1018.47  80.03
6  10.80  41.39  1019.74  74.08
7   9.64  39.35  1015.10  91.76
8  11.53  41.14  1025.63  88.54
9  21.83  63.07  1011.57  87.02

In [67]:
# unseen_dataset
unseen_dataset = unseen_dataset_df.iloc[:, :].values
unseen_dataset

array([[  12.45,   40.56, 1017.84,   66.52],
       [  16.7 ,   40.56, 1019.04,   50.9 ],
       [  19.88,   44.6 , 1015.52,   37.85],
       [  19.64,   46.33, 1013.33,   98.99],
       [  20.01,   59.87, 1019.  ,   84.12],
       [  16.27,   58.2 , 1018.47,   80.03],
       [  10.8 ,   41.39, 1019.74,   74.08],
       [   9.64,   39.35, 1015.1 ,   91.76],
       [  11.53,   41.14, 1025.63,   88.54],
       [  21.83,   63.07, 1011.57,   87.02],
       [   9.51,   40.46, 1018.84,   70.12],
       [  28.84,   75.6 , 1018.41,   53.96],
       [  25.82,   72.39, 1003.4 ,   86.33],
       [  28.47,   69.23, 1013.18,   40.73],
       [  19.87,   49.69, 1012.23,   68.57],
       [  14.38,   44.84, 1024.59,   81.68],
       [  27.37,   65.06, 1013.09,   50.92],
       [  28.05,   62.6 , 1017.01,   46.46],
       [   8.66,   36.25, 1028.22,   86.96],
       [  16.61,   45.87, 1009.34,   97.93],
       [  11.28,   42.44, 1014.62,   99.78],
       [  21.1 ,   62.66, 1011.19,   83.49],
       [  

In [68]:
# Standard Scaling
unseen_dataset_scaled = standard_scaler.transform(unseen_dataset)
unseen_dataset

array([[  12.45,   40.56, 1017.84,   66.52],
       [  16.7 ,   40.56, 1019.04,   50.9 ],
       [  19.88,   44.6 , 1015.52,   37.85],
       [  19.64,   46.33, 1013.33,   98.99],
       [  20.01,   59.87, 1019.  ,   84.12],
       [  16.27,   58.2 , 1018.47,   80.03],
       [  10.8 ,   41.39, 1019.74,   74.08],
       [   9.64,   39.35, 1015.1 ,   91.76],
       [  11.53,   41.14, 1025.63,   88.54],
       [  21.83,   63.07, 1011.57,   87.02],
       [   9.51,   40.46, 1018.84,   70.12],
       [  28.84,   75.6 , 1018.41,   53.96],
       [  25.82,   72.39, 1003.4 ,   86.33],
       [  28.47,   69.23, 1013.18,   40.73],
       [  19.87,   49.69, 1012.23,   68.57],
       [  14.38,   44.84, 1024.59,   81.68],
       [  27.37,   65.06, 1013.09,   50.92],
       [  28.05,   62.6 , 1017.01,   46.46],
       [   8.66,   36.25, 1028.22,   86.96],
       [  16.61,   45.87, 1009.34,   97.93],
       [  11.28,   42.44, 1014.62,   99.78],
       [  21.1 ,   62.66, 1011.19,   83.49],
       [  

In [69]:
y_pred_unseen = regressor.predict(unseen_dataset_scaled)
y_pred_unseen

array([473.27653664, 467.42705403, 462.05153816, 452.15393346,
       450.95051848, 459.39290014, 475.25184993, 474.91521208,
       471.88752588, 445.67350725, 478.61473432, 434.52821851,
       435.1778034 , 438.58377566, 455.73123407, 466.39934483,
       440.10736408, 440.29031306, 479.14655636, 458.20788134,
       469.61212689, 447.76412051, 461.31974574, 430.268134  ,
       480.32699342, 436.97689207, 453.77455479, 453.51525088,
       442.39347123, 435.18830668, 461.4441645 , 431.58042869,
       444.98218769, 447.0121156 , 437.81628668, 470.08217907,
       467.74395296, 427.00810701, 451.25852629, 434.74457481,
       445.67173145, 451.73693719, 467.88063183, 448.32614508,
       424.89549633, 436.63178724, 430.73685357, 447.41171227,
       464.13894906, 471.2423451 , 434.22629215, 442.14485007,
       439.56641149, 435.10671666, 477.49280141, 472.32642688,
       441.13635689, 469.28683834, 446.00371616, 465.92279182,
       470.24748184, 445.41097088, 440.03465702, 480.36

In [70]:
y_pred_unseen_df = pd.DataFrame(y_pred_unseen, columns=["Tahmini_Output"])
y_pred_unseen_df.head(10)

Tahmini_Output
0      473.276537
1      467.427054
2      462.051538
3      452.153933
4      450.950518
5      459.392900
6      475.251850
7      474.915212
8      471.887526
9      445.673507

In [71]:
all_df = unseen_dataset_df.merge(y_pred_unseen_df, how="left", left_index=True, right_index=True)
all_df

AT      V       AP     RH  Tahmini_Output
0   12.45  40.56  1017.84  66.52      473.276537
1   16.70  40.56  1019.04  50.90      467.427054
2   19.88  44.60  1015.52  37.85      462.051538
3   19.64  46.33  1013.33  98.99      452.153933
4   20.01  59.87  1019.00  84.12      450.950518
..    ...    ...      ...    ...             ...
95  20.97  47.43  1007.64  71.18      453.388950
96  14.10  41.16  1021.26  73.87      468.882187
97  17.83  66.86  1011.65  77.31      454.282147
98   8.46  40.80  1023.57  81.27      479.106448
99  30.92  78.05  1011.00  59.62      428.469714

[100 rows x 5 columns]