# Decision Tree Regression

In [1]:
import numpy as np
import pandas as pd

In [3]:
# veriyi oku
df = pd.read_csv('Power_Plant.csv', delimiter=",")
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [4]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [5]:
# Veri setini Eğitim seti ve Test seti olarak ayırma

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)
x_train

array([[  30.53,   73.21, 1000.37,   74.17],
       [  23.07,   65.46, 1014.07,   46.77],
       [  20.68,   42.04, 1010.2 ,   63.43],
       ...,
       [  23.09,   51.19, 1009.4 ,   81.61],
       [  22.06,   45.61, 1014.3 ,   77.75],
       [  13.48,   46.18, 1018.15,   88.38]])

In [6]:
# Algoritmayı eğit

from sklearn.tree import DecisionTreeRegressor

regressor = DecisionTreeRegressor(random_state=0)

regressor.fit(x_train, y_train)

DecisionTreeRegressor(random_state=0)

In [7]:
#Test verilerini kullanarak çıktıyı tahmin et

y_pred = regressor.predict(x_test)
print(y_pred)

[438.79 452.5  431.77 ... 450.55 457.88 439.12]


In [8]:
y_pred_df = pd.DataFrame(data=y_pred,columns=["Tahmini_Sonuc"])

In [9]:
y_test_df = pd.DataFrame(data=y_test,columns=["Gerçek_Sonuç"])

karsılastırma_df = pd.concat([y_test_df,y_pred_df],axis=1)
karsılastırma_df

Gerçek_Sonuç  Tahmini_Sonuc
0           440.17         438.79
1           450.86         452.50
2           441.76         431.77
3           464.95         468.80
4           467.62         470.23
...            ...            ...
1889        430.92         428.74
1890        466.83         469.52
1891        446.75         450.55
1892        449.99         457.88
1893        440.46         439.12

[1894 rows x 2 columns]

In [10]:
# Modelin değerlendirilmesi

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9293764338795556

In [11]:
unseen_dataset_df = pd.read_csv('Power_Plant_Unseen.csv', delimiter=";")
unseen_dataset_df.head(10)

AT      V       AP     RH
0  12.45  40.56  1017.84  66.52
1  16.70  40.56  1019.04  50.90
2  19.88  44.60  1015.52  37.85
3  19.64  46.33  1013.33  98.99
4  20.01  59.87  1019.00  84.12
5  16.27  58.20  1018.47  80.03
6  10.80  41.39  1019.74  74.08
7   9.64  39.35  1015.10  91.76
8  11.53  41.14  1025.63  88.54
9  21.83  63.07  1011.57  87.02

In [12]:
# unseen_dataset
unseen_dataset = unseen_dataset_df.iloc[:, :].values
unseen_dataset

array([[  12.45,   40.56, 1017.84,   66.52],
       [  16.7 ,   40.56, 1019.04,   50.9 ],
       [  19.88,   44.6 , 1015.52,   37.85],
       [  19.64,   46.33, 1013.33,   98.99],
       [  20.01,   59.87, 1019.  ,   84.12],
       [  16.27,   58.2 , 1018.47,   80.03],
       [  10.8 ,   41.39, 1019.74,   74.08],
       [   9.64,   39.35, 1015.1 ,   91.76],
       [  11.53,   41.14, 1025.63,   88.54],
       [  21.83,   63.07, 1011.57,   87.02],
       [   9.51,   40.46, 1018.84,   70.12],
       [  28.84,   75.6 , 1018.41,   53.96],
       [  25.82,   72.39, 1003.4 ,   86.33],
       [  28.47,   69.23, 1013.18,   40.73],
       [  19.87,   49.69, 1012.23,   68.57],
       [  14.38,   44.84, 1024.59,   81.68],
       [  27.37,   65.06, 1013.09,   50.92],
       [  28.05,   62.6 , 1017.01,   46.46],
       [   8.66,   36.25, 1028.22,   86.96],
       [  16.61,   45.87, 1009.34,   97.93],
       [  11.28,   42.44, 1014.62,   99.78],
       [  21.1 ,   62.66, 1011.19,   83.49],
       [  

In [13]:
y_pred_unseen = regressor.predict(unseen_dataset)
y_pred_unseen

array([475.86, 467.46, 460.59, 452.82, 444.71, 458.31, 473.77, 481.96,
       474.75, 443.41, 486.34, 441.04, 432.77, 435.62, 456.64, 465.48,
       440.51, 443.24, 480.31, 455.96, 468.64, 446.02, 457.75, 437.4 ,
       481.6 , 444.83, 450.17, 451.19, 444.77, 434.48, 461.57, 425.91,
       442.78, 455.41, 438.42, 472.42, 470.69, 434.15, 454.26, 437.06,
       438.89, 451.88, 463.06, 438.89, 433.94, 429.93, 435.43, 442.15,
       460.48, 471.78, 436.85, 438.92, 437.93, 433.48, 473.31, 480.87,
       439.6 , 471.1 , 442.32, 466.47, 458.49, 447.16, 434.05, 483.71,
       439.13, 437.7 , 446.49, 437.55, 477.14, 428.72, 431.09, 437.48,
       443.9 , 452.89, 470.48, 465.47, 465.49, 457.05, 433.42, 468.51,
       487.92, 447.76, 475.01, 462.73, 441.66, 450.68, 451.96, 438.  ,
       448.27, 443.66, 431.35, 444.62, 460.18, 468.87, 451.42, 450.  ,
       459.84, 451.19, 475.46, 435.17])

In [14]:
y_pred_unseen_df = pd.DataFrame(y_pred_unseen, columns=["Tahmini_Output"])
y_pred_unseen_df.head(10)

Tahmini_Output
0          475.86
1          467.46
2          460.59
3          452.82
4          444.71
5          458.31
6          473.77
7          481.96
8          474.75
9          443.41

In [15]:
all_df = unseen_dataset_df.merge(y_pred_unseen_df, how="left", left_index=True, right_index=True)
all_df

AT      V       AP     RH  Tahmini_Output
0   12.45  40.56  1017.84  66.52          475.86
1   16.70  40.56  1019.04  50.90          467.46
2   19.88  44.60  1015.52  37.85          460.59
3   19.64  46.33  1013.33  98.99          452.82
4   20.01  59.87  1019.00  84.12          444.71
..    ...    ...      ...    ...             ...
95  20.97  47.43  1007.64  71.18          450.00
96  14.10  41.16  1021.26  73.87          459.84
97  17.83  66.86  1011.65  77.31          451.19
98   8.46  40.80  1023.57  81.27          475.46
99  30.92  78.05  1011.00  59.62          435.17

[100 rows x 5 columns]